# i3status configuration file.
# see "man i3status" for documentation.
 
# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!
 
general {
        colors = true
        interval = 1
        color_good = "#F9FAF9"
        color_bad = "#F9FAF9"
        color_degraded = "#DC322F"
}
py3status {
    nagbar_font = 'pango:Ubuntu Mono 12'
      on_udev_drm = "refresh_and_freeze"
}
 
 order += "external_script power"
order += "backlight"
order += "volume_status"
order += "tztime local"
order += "keyboard_layout" 
order += "net_rate"
order += "ethernet _first_"
order += "vpn_status"
order += "wifi"
volume_status {
    cache_timeout=0
    thresholds = [
        (0, "#FF0000"),
        (20, "#E2571E"),
        (30, "#FF7F00"),
        (40, "#FFFF00"),
        (60, "#00FF00"),
        (80, "#96BF33"),
        (100, "#0000FF"),
        (120, "#4B0082"),
        (140, "#8B00FF"),
        (150, "#FFFFFF")
    ]
}
external_script power {
format= "power"
script_path="~/.config/scripts/power.sh"
on_click 1= "exec ~/.config/scripts/power.sh menu"
}
keyboard_layout {
cache_timeout = 0
}
 
wifi {
        format = "  {ssid} {signal_percent}|W: down"
} 
 
ethernet _first_ {
# if you use %speed, i3status requires root privileges
        format_up = "  eth (%ip) "
        format_down = ""
}
 
net_rate {
    unit = "KB/s"
    format_value = "[\?min_length=10 {value:.1f} {unit}]"
    si_units = "True"
    format = "{down}⇣ {up}⇡"
}
  
tztime local {
        # format = "%Y-%m-%d %H:%M:%S"
        format = "                      %m/%d %a %H:%M                       "
}
