# i3status configuration file.
# see "man i3status" for documentation.
 
# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!
 
general {
        colors = true
        interval = 1
        color_good = "#000000"
        color_degraded = "#2238FF"
        color_bad = "#FF0000"
}
 
order += "load"
order += "cpu_usage"
# order += "diskdata"
order += "load"
order += "external_script"
order += "external_script mine"
# order += "mpd_status"
# mpd_status {
# port ="6601"
# format = "{time}-{artist}-{title}"
# }

cpu_usage {
        format = "  %usage "
}
 
load {
        format = " load %1min "
        # max_threshold = 0.3
}
 
diskdata {
    prefix_type = decimal
  #format_space = "[\?min_length=5 {value:.2f}]"
    format = " ⛁ {used_percent}% (U:{used} GB, F:{free} GB) "
}

external_script {
        format = "{output}"
        script_path = "~/.config/scripts/redshift.sh --output"
        on_click 1 = "exec ~/.config/scripts/redshift.sh --toggle"
        cache_timeout = 8
}

external_script mine {
        format = "clipboard"
        script_path = "~/.config/scripts/rofi.sh "
        on_click 1 = "exec ~/.config/scripts/rofi.sh clip "
        cache_timeout = 8
}
