
#active-opacity = 0.8;


# Fading
# experimental-backend=true
fading = false;			        # Fade windows during opacity changes.
fade-delta = 5;		        # The time between steps in a fade in milliseconds. (default 10).
fade-in-step = 0.03;		    # Opacity change between steps while fading in. (default 0.028).
fade-out-step = 0.03;		    # Opacity change between steps while fading out. (default 0.03).
# blur-background = true
# Blur
# blur: {
#     method = "kawase";
#     strength = 20;
#     background = false;
#     background-frame = false;
#     background-fixed = false;
# }
# blur-background-exclude = [
# 	"class_g = 'Polybar'"
# ];

# blur-rule = [
#     "class_g = 'Rofi'"
# ];
# Other

mark-wmwin-focused = true;   	# Try to detect WM windows and mark them as active.
mark-ovredir-focused = true; 
detect-rounded-corners = true;
detect-client-opacity = true;
glx-no-stencil = true;
unredir-if-possible = true;
# glx-copy-from-front = false;
no-fading-openclose=true
refresh-rate = 60;
vsync = true;
EnablePageFlip = true;
backend = "xrender";
#################################
#
# Shadows
#
#################################
shadow = true;
# Enable mild shadow
shadow-radius = 12;
shadow-opacity = 0.2;
shadow-offset-x = -7;
shadow-offset-y = -17;
shadow-exclude = [
    "! name~=''",
    "name = 'Notification'",
    "class_g = 'firefox' && argb",
    "name *= 'Chrome'",
    "name * = 'Firefox'",
    "class_g= 'Ulauncher'",
    "class_g ?= 'Notify-osd'",
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"

];
# Avoid drawing shadow on all shaped windows (see also: --detect-rounded-corners)
shadow-ignore-shaped = true;
########################
# Window type settings #
########################

wintypes:
{
  dock = {
  shadow = false;
  },
 dnd = {
 opacity = false;
 corner-radius=0;
 },
 popup_menu = {
 opacity = false;
corner-radius = 0 ;
},

 dropdown_menu = {
 opacity = false;
 shadow = false;
},
tooltip = {
    corner-radius = 0 ;
    }
};
xrender-sync-fence = true;
# corner-radius = 12;
# rounded-corners-exclude = [
#   "class_g = 'i3'",
#   "class_g = 'Polybar'",
#   "class_g = 'sublime_text'",
#   "class_g = 'Firefox'",
#   "class_g = 'Thunderbird'",
#  "class_g = 'i3bar'",
#  "class_g = 'Rofi'",
#   "class_g = 'i3-frame'",
#  "class_g = 'xob'"
# ];
# round-borders = 1;
# round-borders-rule = [
#   "3:window_type = 'unknown'",
#   "3:window_type = 'toolbar'",
#   "3:window_type = 'utility'",
#   "3:window_type = 'splash'",
#   "3:window_type = 'dialog'",
#   "3:window_type = 'normal'"
# ];

