#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         1
bspc config window_gap          10 

bspc config split_ratio          0.52
bspc config automatic_scheme longest_side
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config top_padding 0
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true 
bspc config active_border_color '#273238'
bspc config normal_border_color '#273238'
bspc config focused_border_color '#ffffff'
bspc config presel_feedback_color '#273238'
# ~/.config/scripts/startup.sh
killall -q copyq
killall -q picom
killall -q nm-applet
~/.config/polybar/launch.sh
nitrogen --set-tiled ~/Pictures/background.jpg
numlockx on
dunst &
copyq &
nm-applet &
setxkbmap -option 'grp:alt_shift_toggle,caps:swapescape' -layout us,ir
picom -b --experimental-backend &
mkfifo /tmp/xobvolume
# tail -f /tmp/xobbacklight | xob -c ~/.config/xob_brightness
tail -f /tmp/xobvolume | xob -c ~/.config/xob_volume &
# [ -p /tmp/xobbrightness] && { tail -f /tmp/xobbrightness | xob -c ~/.config/xob_brightness &}
# [ -p /tmp/xobvolume] && { tail -f /tmp/xobvolume | xob -c ~.config/xob_volume & }
# tail -f /tmp/xobbrightness | xob -c ~/.config/xob_brightness &
# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^1'
bspc rule -a Sublime-merge desktop='^2'
bspc rule -a Sublime_text desktop="^2"
bspc rule -a Zeal desktop='^3'
bspc rule -a sqlitebrowser desktop='^3'
bspc rule -a cantata desktop='^4'
bspc rule -a copyq state=floating
bspc rule -a telegram-desktop state=floating
bspc rule -a TelegramDesktop state=floating
# bspc rule -a Screenkey manage=off
