#!/usr/bin/env bash


ssid=`nmcli device status |grep wifi| awk '{print$4}'`
disconnected=""
wireless_connected=""
vpn_connected=""

while true; do
wifi="$(ip link | grep wlp9s0 | grep 'state UP')"
vpn="$( ip link | grep vpn0 | grep 'state UP')"
    if (ping -c 1 8.8.8.8) &>/dev/null; then
        if [[ $vpn && $wifi ]];then
            echo "$vpn_connected" $ssid ; sleep 5;
        elif [[ $wifi ]]; then
            echo "$wireless_connected" $ssid; sleep 5;
        else
            echo " eth"; sleep 5;
        fi
    else
        echo "$disconnected";sleep 2;
    fi
done
