-- don't load the plugins below
vim.g.loaded_2html_plugin = 1
vim.g.loaded_gzip = 1
vim.g.loaded_matchit = 1
vim.g.loaded_matchparen = 1
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.g.loaded_tar = 1
vim.g.loaded_tarPlugin = 1
vim.g.loaded_zipPlugin = 1

-- vim.opt.clipboard = "unnamedplus" -- sync with system clipboard
vim.opt.arabicshape = false
vim.opt.completeopt = "menu,menuone"
vim.opt.cursorline = true -- Enable highlighting of the current line
vim.opt.encoding = "utf-8"
vim.opt.expandtab = true -- Use spaces instead of tabs
vim.opt.hidden = true -- Enable modified buffers in background
vim.opt.ignorecase = true -- Ignore case
vim.opt.joinspaces = false -- No double spaces with join after a dot
vim.opt.matchtime = 4
vim.opt.mouse = "a" -- enable mouse mode
vim.opt.number = true -- Print line number
vim.opt.numberwidth = 3 -- Print line number
vim.opt.relativenumber = true -- Relative line numbers
vim.opt.ruler = false
vim.opt.scrolloff = 8 -- Lines of context
vim.opt.shiftround = true -- Round indent
vim.opt.shiftwidth = 4
vim.opt.showmatch = true
vim.opt.showcmd = false
vim.opt.showmode = false
vim.opt.sidescrolloff = 8 -- Columns of context
vim.opt.signcolumn = "yes:2"
vim.opt.smartcase = true -- Don't ignore case with capitals
vim.opt.smartindent = true -- Insert indents automatically
vim.opt.softtabstop = 4
vim.opt.tabstop = 4
vim.opt.termguicolors = true -- True color support
vim.opt.whichwrap = "b,s,<,>,[,]"
vim.opt.wildignorecase = true
vim.opt.wildmenu = true
vim.opt.wildmode = "longest:full,full" -- Command-line completion mode
vim.opt.wrap = true -- Enable line wrap
vim.opt.guifont = "JetBrains Mono,Iosevka Term:h13"
-- vim.opt.guifont = "FiraCode Nerd Font:h12"
-- vim.opt.foldexpr = "nvim_treesitter#foldexpr()" -- TreeSitter folding
-- vim.opt.foldmethod = "expr" -- TreeSitter folding
-- vim.opt.foldlevel = 1
