-- don't load the plugins below
vim.g.loaded_2html_plugin = 1
vim.g.loaded_getscript = 1
vim.g.loaded_getscriptPlugin = 1
vim.g.loaded_gzip = 1
vim.g.loaded_logiPat = 1
vim.g.loaded_matchit = 1
vim.g.loaded_matchparen = 1
vim.g.loaded_netrw = 1
vim.g.loaded_netrwFileHandlers = 1
vim.g.loaded_netrwPlugin = 1
vim.g.loaded_netrwSettings = 1
vim.g.loaded_rrhelper = 1
vim.g.loaded_tar = 1
vim.g.loaded_tarPlugin = 1
vim.g.loaded_vimball = 1
vim.g.loaded_vimballPlugin = 1
vim.g.loaded_zip = 1
vim.g.loaded_zipPlugin = 1

vim.g.loaded_node_provider = 0
vim.g.loaded_perl_provider = 0
vim.g.loaded_python3_provider = 0
vim.g.loaded_python_provider = 0
vim.g.loaded_ruby_provider = 0
-- vim.opt.clipboard = "unnamedplus" -- sync with system clipboard
vim.opt.arabicshape = false
vim.opt.completeopt = "menu,menuone,preview"
vim.opt.cmdheight = 0
vim.opt.cursorline = true -- Enable highlighting of the current line
vim.opt.encoding = "utf-8"
vim.opt.fillchars = { eob = " " }
vim.opt.expandtab = true -- Use spaces instead of tabs
vim.opt.ignorecase = true -- Ignore case
vim.opt.listchars:append("tab:->,space:.")
vim.opt.mouse = "a" -- enable mouse mode
vim.opt.number = true -- Print line number
vim.opt.relativenumber = true -- Relative line numbers
vim.opt.ruler = false
vim.opt.scrolloff = 8 -- Lines of context
vim.opt.shiftround = true -- Round indent
vim.opt.shiftwidth = 4
vim.opt.showmatch = true
vim.opt.showcmd = false
vim.opt.showmode = false
vim.opt.signcolumn = "yes:2"
vim.opt.smartcase = true -- Don't ignore case with capitals
vim.opt.smartindent = true -- Insert indents automatically
vim.opt.termguicolors = true -- True color support
vim.opt.undofile = true -- persist undo tree for eachfile
vim.opt.whichwrap = "b,s,<,>,[,]"
vim.opt.wildignorecase = true
-- vim.opt.foldmethod = "indent" -- TreeSitter folding
-- vim.opt.foldlevel = 1
-- vim.opt.foldexpr = "nvim_treesitter#foldexpr()" -- TreeSitter folding
