set ai
set autoread
set clipboard=unnamedplus
set cursorline
set encoding=utf-8
set expandtab
set hidden
set ignorecase
set mouse=a
set noshowmode
set number
set numberwidth=3
set relativenumber
set shiftwidth=4
set showmatch
set smartcase
set smartindent
set softtabstop=4
set t_CO=256
set tabstop=4
set termguicolors
set title
set whichwrap=b,s,<,>,[,]
set wildignorecase
set wildmenu
set wrap
